### PR TITLE
Fixing filename to match other documents.  Also escaping underscores …

### PR DESCRIPTION
**Pull request by jasoncarlsen**
…in header text.

### CODE REVIEW

**Comment by jasoncarlsen** [comment]
My apologies for the churn here.  I noticed the documentation wasn't showing up on the website and I assume it's because I was missing the ".html" portion of the filename.

**Comment by ringods** [comment]
@jasoncarlsen while you are at it, may I ask you for another small change in the test suite?

You currently have this:

https://github.com/terraform-providers/terraform-provider-gitlab/blob/555e4be00717ddc9e08c1982ff3465195a4596eb/gitlab/resource_gitlab_group_ldap_link_test.go#L28-L29

Which leads to confusing output because it mentions error and warning in a single line:

```
=== RUN   TestAccGitlabGroupLdapLink_basic
##[error]    TestAccGitlabGroupLdapLink_basic: resource_gitlab_group_ldap_link_test.go:29: [WARNING] Skipping test until test data is configured in testdata/resource_gitlab_group_ldap_link.json.
```

May I ask you to make replace the `if`/`else` with a custom `SkipFunc` where this check is integrated and not print out the warning? The custom `SkipFunc` should then be the logical `AND` of `isRunningInCE` and your `if` test.

**Comment by ringods** [comment]
And you may ignore the test failure. I'm investigating this in #319

**Comment by jasoncarlsen** [comment]
@ringods Sure I can do that.  I'll carve out some time this week to get it done.

**Comment by ringods** [comment]
@jasoncarlsen meanwhile, I merged this fix. You can open a new PR for the test request.

**Pull request merged**
