### PR TITLE
Stop silently deleting objects from state

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
@attachmentgenie @jorcau can you review this?

**Comment by jorcau** [comment]
I'm not sure to understand why you want to avoid this behavior. It seems okay to me to remove from state resources that no longer exist. Am I missing something?

**Comment by roidelapluie** [comment]
Yes. Gitlab will return 404 if the user has no right so see the resources (instead of 404).

If people use their own oauth token to run this it will be an issue.

**Comment by jorcau** [comment]
Ok, it makes sense then!

I'm just a bit worried about the behavior in case resources have been removed using the UI. If I'm not making a mistake, it means that all Terraform actions will fail unless something like a `terraform state rm <removed_resource>` is done, right?

Knowing this, I'd rather like to keep the custom error message on 404 errors and make it more explicit about the 404 / 403 Gitlab errors meaning, so users know what's happening.

**Comment by jakubknejzlik** [comment]
@jorcau imho it's standard behaviour in other providers ("if you remove it manually, you also have to fix the TF state").

**Comment by roidelapluie** [comment]
I will merge it and mark it as breaking in the release notes.

**Pull request merged**
