### PR TITLE
Add push rules

### PR DESCRIPTION
**Pull request by bilby91**
I started to write integration tests for this one but realized that this feature requires the `Starter` GitLab plan so I don't think we can run this tests. If that is not the case I'll be happy to add them.

### CODE REVIEW

**Comment by roidelapluie** [comment]
I will get in touch with @gitlabhq about this.

**Comment by bilby91** [comment]
@roidelapluie Awesome!

**Comment by roidelapluie** [comment]
https://gitlab.com/gitlab-com/marketing/community-relations/gitlab-oss/merge_requests/348

**Comment by bilby91** [comment]
@roidelapluie Any progress on this ?

**Comment by six-arm** [comment]
I just submitting a PR for push rules too.  Let me know how you'd like to proceed.  https://github.com/terraform-providers/terraform-provider-gitlab/pull/163

I'm talking to my gitlab contact about a license for testing this too.  Let me know if I can help.

**Comment by bilby91** [comment]
@six-arm @roidelapluie I still think we are missing the license. Anything we can do to accelerate this?

**Comment by six-arm** [comment]
I've brought https://gitlab.com/gitlab-com/marketing/community-relations/gitlab-oss/merge_requests/348 to the attention of my gitlab contacts.  Let's see if we can get an option to test EE.

**Pull request closed without merging**
