### PR TITLE
Add Group Membership, Group Variable, fix Project Variable, refactor Project Membership

### PR DESCRIPTION
**Pull request by sudoapt-getclean**
I have added a Group Membership based on the Project Membership but than refactored it and fixed the importing,. I also decided to do this for Project Membership

I merged @thibault-yellowstones project variables. made them work (they where not storing id's) and than made the group variable resource based on this.

There is documentation and a change log.

Most important thing left are tests for the import I still have to figure out how to do this.
this merge requests supersedes #59 

I updated the dependency on xanxy/go-gitlab to the latest because i needed group variable support

I would be happy to make changes if anybody has suggestions.

### CODE REVIEW

**Comment by roidelapluie** [comment]
I will have a look this week, thanks

**Comment by aloisbarreras** [comment]
+1

**Comment by sudoapt-getclean** [comment]
@roidelapluie What did you think?
There is actually some other stuff that I also would like to pickup when this is merged. but i don't want to turn this thing into some monster merge.

**Comment by sudoapt-getclean** [comment]
@roidelapluie can we come to some solution to start moving things forward?

**Comment by roidelapluie** [comment]
Let's move on ! :)

**Pull request merged**
