### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
upp #126

**Comment by matejvelikonja** [comment]
Out of curiosity, why my PR (#126) was no good?

**Comment by roidelapluie** [comment]
+36,575 −4,523 
vs 
+12,709 −12,767

**Comment by roidelapluie** [comment]
I do not know why a so big difference

**Comment by roidelapluie** [comment]
mmh now +105,199 −6,750

**Comment by matejvelikonja** [comment]
Well, I've run only

```bash
go get -u github.com/xanzy/go-gitlab
```
and
```bash
go mod vendor
```

**Pull request merged**
