### PR TITLE
add attribute remove_source_branch_after_merge to projects

### LINKED ISSUE #200: Support for option "remove_source_branch_after_merge" for projects
Since [merge request](https://gitlab.com/gitlab-org/gitlab/merge_requests/18408) is merged GitLab API will have option `force_remove_source_branch` in the API.
It gonna be rather cool to be in touch with fresh changes in GitLab API and support this option.

### Affected Resource(s)
Please list the resources as a list, for example:
- `gitlab_project`

### Terraform Configuration Files
```hcl
resource "gitlab_project" "some-project" {
...
  force_remove_source_branch = true
}
```

### References
https://gitlab.com/gitlab-org/gitlab/issues/18283
https://gitlab.com/gitlab-org/gitlab/merge_requests/18408

### PR DESCRIPTION
**Pull request by apricote**
Closes #200

### CODE REVIEW

**Comment by apricote** [comment]
I rebased on the current `master` (that includes `xanzy/go-github@0.30.1`) and the PR is no longer blocked. All Unit Tests are green.

**Comment by ringods** [comment]
Hello @apricote, can you rebase once more? Based on the test result outcome, I will merge shortly after that.

**Comment by apricote** [comment]
@ringods I rebased on current master (`bef89771b574ec408f067b625a92bdb38cd3c589`) but the CI failures are not related to the resource I modified.

**Comment by ringods** [comment]
@apricote can you rebase once more? Branch `master` contains an updated `go-gitlab` library which already fixes one test. But due to #319, it is possible another test can still fail but I will ignore that for merging this PR.

**Comment by apricote** [comment]
Done @ringods. Acceptence Tests for ce look fine now. Thanks for your work on this project :)

**Comment by ringods** [comment]
Tnx for the contribution.

**Pull request merged**
