### PR TITLE
Bump go-gitlab to v0.16.1

### PR DESCRIPTION
**Pull request by bilby91**

### CODE REVIEW

**Comment by bilby91** [comment]
Test are passing except for the already known cluster test issue #112 

```
=== RUN   TestAccDataGitlabProject_basic
--- PASS: TestAccDataGitlabProject_basic (8.00s)
=== RUN   TestAccDataGitlabUser_basic
--- PASS: TestAccDataGitlabUser_basic (1.40s)
=== RUN   TestAccDataSourceGitlabUsers_basic
--- PASS: TestAccDataSourceGitlabUsers_basic (3.69s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGitlabDeployKey_basic
--- PASS: TestAccGitlabDeployKey_basic (13.58s)
=== RUN   TestAccGitlabDeployKey_suppressfunc
--- PASS: TestAccGitlabDeployKey_suppressfunc (9.09s)
=== RUN   TestAccGitlabGroupMembership_basic
--- PASS: TestAccGitlabGroupMembership_basic (11.74s)
=== RUN   TestAccGitlabGroup_basic
--- PASS: TestAccGitlabGroup_basic (10.47s)
=== RUN   TestAccGitlabGroup_import
--- PASS: TestAccGitlabGroup_import (6.53s)
=== RUN   TestAccGitlabGroup_nested
--- PASS: TestAccGitlabGroup_nested (33.83s)
=== RUN   TestAccGitlabGroupVariable_basic
--- PASS: TestAccGitlabGroupVariable_basic (8.39s)
=== RUN   TestAccGitlabLabel_basic
--- PASS: TestAccGitlabLabel_basic (13.90s)
=== RUN   TestAccGitlabPipelineTrigger_basic
--- PASS: TestAccGitlabPipelineTrigger_basic (12.10s)
=== RUN   TestAccGitlabProjectCluster_basic
--- FAIL: TestAccGitlabProjectCluster_basic (7.23s)
    testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:

        * gitlab_project_cluster.foo: 1 error(s) occurred:

        * gitlab_project_cluster.foo: POST http://gitlab.example.com:8001/api/v4/projects/7/clusters/user: 404 {error: 404 Not Found}
=== RUN   TestAccGitlabProjectCluster_import
--- FAIL: TestAccGitlabProjectCluster_import (7.29s)
    testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:

        * gitlab_project_cluster.foo: 1 error(s) occurred:

        * gitlab_project_cluster.foo: POST http://gitlab.example.com:8001/api/v4/projects/8/clusters/user: 404 {error: 404 Not Found}
=== RUN   TestAccGitlabProjectHook_basic
--- PASS: TestAccGitlabProjectHook_basic (10.34s)
=== RUN   TestAccGitlabProjectMembership_basic
--- PASS: TestAccGitlabProjectMembership_basic (12.26s)
=== RUN   TestAccGitlabProject_basic
--- PASS: TestAccGitlabProject_basic (25.72s)
=== RUN   TestAccGitlabProject_import
--- PASS: TestAccGitlabProject_import (9.21s)
=== RUN   TestAccGitlabProject_nestedImport
--- PASS: TestAccGitlabProject_nestedImport (14.15s)
=== RUN   TestAccGitlabProjectVariable_basic
--- PASS: TestAccGitlabProjectVariable_basic (10.84s)
=== RUN   TestAccGitlabUser_basic
--- PASS: TestAccGitlabUser_basic (2.61s)
=== RUN   TestGitlab_validation
--- PASS: TestGitlab_validation (0.00s)
=== RUN   TestGitlab_visbilityHelpers
--- PASS: TestGitlab_visbilityHelpers (0.00s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-gitlab/gitlab	232.410s
```

**Comment by bilby91** [comment]
I'm getting `401` errors when running test on CI. Has something changed in the CI environment recently that could be causing this ?

**Comment by matejvelikonja** [comment]
@bilby91 https://github.com/terraform-providers/terraform-provider-gitlab/issues/110

**Comment by bilby91** [comment]
Thanks @matejvelikonja . Should we wait on that one to get addressed then ?

**Comment by matejvelikonja** [comment]
That one will not be resolved until new GitLab version with mentioned fixed will be released.
In my opinion, if you tested the acceptance tests locally and it works I don't see a problem merging this.
But I am not a maintainer of this project, so it's not my call.

**Comment by bilby91** [comment]
@matejvelikonja Got it! Thanks for the quick reply either way ;) 

Will wait for some response of a maintainer then!

**Comment by roidelapluie** [comment]
Hello, I will work on that next week

**Comment by bilby91** [comment]
@roidelapluie Any progress or anything I can help ?

**Comment by matejvelikonja** [comment]
@bilby91 could you please test changes with master version of `go-gitlab`, so we can bump it to the latest version?
@svanharmelen will release a new version of go-gitlab once we test it out.

Ref: https://github.com/xanzy/go-gitlab/pull/614#issuecomment-486548077

**Comment by roidelapluie** [comment]
Hello, #118 is ready for review

**Comment by roidelapluie** [comment]
pending #118 is merged for green CI test

**Comment by roidelapluie** [comment]
Thanks!

**Comment by bilby91** [comment]
@roidelapluie Hey! Thanks for taking the time to get the CI passing :)

Is there any ETA for a new release ? Are we waiting for any particular PR to land on master ?

**Comment by roidelapluie** [comment]
The new release is here @bilby91

**Comment by bilby91** [comment]
@roidelapluie 🎉

**Pull request merged**
