### PR TITLE
Add kubernetes group clusters

### LINKED ISSUE #138: gitlab_group_cluster resource
Please create a gitlab_group_cluster resource to be able to configure a kubernetes cluster at the group level.

### PR DESCRIPTION
**Pull request by magic7s**
Add resource `gitlab_group_cluster` modeled after `gitlab_project_cluster`. Find and replace was the main method used. 

I added `vendor/github.com/xanzy/go-gitlab/group_clusters.go` but I assume a PR needs to be made in that repo. 

All tests have passed and tested it against gitlab.com test environment. 

closes #138

### CODE REVIEW

**Comment by roidelapluie** [comment]
have you tested it?

**Comment by magic7s** [comment]
@roidelapluie yes, I have it working in a demo project on GitLab.com. I haven't tried to beat it to death, but add/remove/update are all working.

**Comment by roidelapluie** [comment]
can you remove vendor / from this PR?

**Comment by magic7s** [comment]
@roidelapluie Removed but now the build now the build fails. You need to pull from upstream.

**Comment by roidelapluie** [comment]
I rebased this PR

**Comment by roidelapluie** [comment]
upstream has not release yet

**Comment by magic7s** [comment]
https://github.com/xanzy/go-gitlab/pull/668

**Comment by magic7s** [comment]
Dependencies have been released. https://github.com/xanzy/go-gitlab/releases/tag/v0.21.0

**Comment by magic7s** [comment]
Depends on https://github.com/terraform-providers/terraform-provider-gitlab/pull/207

**Comment by magic7s** [comment]
Rebased and re-tested changes. 
```
=== RUN   TestAccGitlabProjectCluster_basic
--- PASS: TestAccGitlabProjectCluster_basic (13.18s)
=== RUN   TestAccGitlabProjectCluster_import
--- PASS: TestAccGitlabProjectCluster_import (7.72s)
```

**Comment by roidelapluie** [comment]
Thanks

**Comment by magic7s** [comment]
@roidelapluie can you create a release? The last was v2.3.0 in Oct

**Comment by vymarkov** [comment]
@roidelapluie would be nice to create a release for this feature, thank you in advance

**Comment by MPV** [comment]
Anyone else getting issues with the `gitlab_group_cluster` resource?
For me, it gets recreated after each apply, saying that the `kubernetes_ca_cert` field has changed every time.

**Comment by roidelapluie** [comment]
Please fill an issue for this instead of commenting merged PR. Thank you.

**Comment by MPV** [comment]
Solved my own issue. ✅ (sorry for the noise here @roidelapluie ) 

For anyone else coming here too: 
I just needed to add `trimspace()` around my cert, like this:

Before:
`base64decode(azurerm_kubernetes_cluster.mycluster.kube_config.0.cluster_ca_certificate)`

After:
`trimspace(base64decode(azurerm_kubernetes_cluster.mycluster.kube_config.0.cluster_ca_certificate))`

**Comment by roidelapluie** [comment]
sounds like a bug. Can you still open an issue?

**Comment by MPV** [comment]
@roidelapluie Ah yes, created: https://github.com/terraform-providers/terraform-provider-gitlab/issues/256

**Pull request merged**
