### PR TITLE
Update go-gitlab dependency to v0.16.1 to fix internal service error …

### PR DESCRIPTION
**Pull request by kchugalinskiy**
This PR fixes problem in project plan application

While getting plan like

```
  ~ gitlab_project.test
      shared_runners_enabled: "false" => "true"
```

Provider is trying to apply request

```
2019-03-13T11:46:12.013+0300 [DEBUG] plugin.terraform-provider-gitlab: {
2019-03-13T11:46:12.013+0300 [DEBUG] plugin.terraform-provider-gitlab:  "shared_runners_enabled": true,
2019-03-13T11:46:12.013+0300 [DEBUG] plugin.terraform-provider-gitlab:  "approvals_before_merge": null
2019-03-13T11:46:12.013+0300 [DEBUG] plugin.terraform-provider-gitlab: }

```

And that leads to server answer

```
2019-03-13T11:46:23.537+0300 [DEBUG] plugin.terraform-provider-gitlab: {
2019-03-13T11:46:23.537+0300 [DEBUG] plugin.terraform-provider-gitlab:  "message": "500 Internal Server Error"
2019-03-13T11:46:23.537+0300 [DEBUG] plugin.terraform-provider-gitlab: }
```

I've already delivered patch to go-gitlab upstream and so this PR updates go-gitlab library to the first error-free semver

### CODE REVIEW

**Comment by kirecek** [comment]
You'll need to update `GetProject` calls since there is breaking change:

Implementation in `14.1`:

```go
func (s *ProjectsService) GetProject(pid interface{}, options ...OptionFunc) (*Project, *Response, error) {
```

Implementation in `16.1`:

```go
func (s *ProjectsService) GetProject(pid interface{}, opt *GetProjectOptions, options ...OptionFunc) (*Project, *Response, error) {
```
I guess tests passed because you haven't updated vendor packages.

**Comment by jorcau** [comment]
Hi @kirecek,

You're totally right! Thanks for noticing this!

We switched to using go modules very recently and I though the Travis CI had stopped using vendors. But it actually still uses them from what I see in the logs: `$ export GOFLAGS=-mod=vendor` (cf. [go doc](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away))

@kchugalinskiy In order to update the vendors you need to run `go mod vendor` (cf. [go doc](https://tip.golang.org/cmd/go/#hdr-Make_vendored_copy_of_dependencies))

**Comment by bilby91** [comment]
Hello,

I'm the responsible for that bug 😒, was troubleshooting the problem yesterday and then realized that there was an open issue already. 

If I can help with anything just let me know, bug was caused by not adding `omitempty` on `approvals_before_merge` and was fixed here => https://github.com/xanzy/go-gitlab/commit/aae307629c64c26b87bf61160dfcab61c8fda5b1

Looking forward on getting this one fixed since it's kind of breaking any update call that doesn't change the `approvals_before_merge`.

**Comment by bilby91** [comment]
Anything that can be done to speed up merging this PR :) ?

**Comment by kirecek** [comment]
:( Let's create a new PR and close this one? Obviously @kchugalinskiy is not active anymore.

**Comment by bilby91** [comment]
Let me create a new one!

**Comment by bilby91** [comment]
@kirecek https://github.com/terraform-providers/terraform-provider-gitlab/pull/114

**Comment by roidelapluie** [comment]
Closing in favour of #114

**Pull request closed without merging**
