### PR TITLE
Add resource for GitHub integration

### PR DESCRIPTION
**Pull request by tptee**
This PR adds a resource for integrating GitHub into a GitLab project. It replicates the patterns from the Jira and Slack resources and uses the Service API via `go-gitlab`.

The GitHub integration is a Premium+ feature, so running the acceptance test is tricky–maybe there's a way to omit it from `make testacc`? Additionally, [this `go-gitlab` PR](https://github.com/xanzy/go-gitlab/pull/749) prevents this resource and its acceptance test from working. When this fix lands upstream (may need a backport because of breaking changes in `0.31.x`, I'll update the PR and run the acceptance test in a Silver .com group!

### CODE REVIEW

**Comment by ringods** [comment]
@tptee can you have a look at the failing acceptance tests?

**Comment by ringods** [comment]
@tptee if your changes need a newer version of `go-gitlab`, please create a separate PR for the dependency bump, including required code changes. Afterwards, rebase this PR to use the newer dependency for new feature development.

**Comment by ringods** [comment]
@tptee for my understanding, is there still a fix needed in `go-gitlab` to make the acceptance tests for the provider working for your PR? If so, does this mean we have to await the next release of `go-gitlab` then?

**Comment by tptee** [comment]
I've pointed to the latest `master` of `go-gitlab` in my branch, but ideally we bump to the upcoming official `0.31.1` release from them. The acceptance tests pass for me locally if I provide a namespace from a Silver plan, but fail in `acceptance-ce`. The GitHub integration is an EE/Silver+ feature, so I think the `/service/github` endpoint doesn't exist in CE, hence the 404s in the test failure:

```
 === RUN   TestAccGitlabServiceGithub_basic
##[error]    TestAccGitlabServiceGithub_basic: testing.go:654: Step 0 error: errors during apply:
        
        Error: PUT http://127.0.0.1:8080/api/v4/projects/24/services/github: 404 {error: 404 Not Found}
        
          on /tmp/tf-test168658687/main.tf line 8:
          (source code not available)
        
        
--- FAIL: TestAccGitlabServiceGithub_basic (5.47s)
=== RUN   TestAccGitlabServiceGithub_import
##[error]    TestAccGitlabServiceGithub_import: testing.go:654: Step 0 error: errors during apply:
        
        Error: PUT http://127.0.0.1:8080/api/v4/projects/25/services/github: 404 {error: 404 Not Found}
        
          on /tmp/tf-test931785609/main.tf line 8:
          (source code not available)
        
        
--- FAIL: TestAccGitlabServiceGithub_import (5.43s)
```

Any guidance for how we can separate EE-only tests from the CE test run?

**Comment by ringods** [comment]
@tptee I filed #314 to investigate how the acceptance tests can be divided in the community and the enterprise editions.

**Comment by roidelapluie** [comment]
> I've pointed to the latest `master` of `go-gitlab` in my branch, but ideally we bump to the upcoming official `0.31.1` release from them. The acceptance tests pass for me locally if I provide a namespace from a Silver plan, but fail in `acceptance-ce`. The GitHub integration is an EE/Silver+ feature, so I think the `/service/github` endpoint doesn't exist in CE, hence the 404s in the test failure:
> 
> ```
>  === RUN   TestAccGitlabServiceGithub_basic
> ##[error]    TestAccGitlabServiceGithub_basic: testing.go:654: Step 0 error: errors during apply:
>         
>         Error: PUT http://127.0.0.1:8080/api/v4/projects/24/services/github: 404 {error: 404 Not Found}
>         
>           on /tmp/tf-test168658687/main.tf line 8:
>           (source code not available)
>         
>         
> --- FAIL: TestAccGitlabServiceGithub_basic (5.47s)
> === RUN   TestAccGitlabServiceGithub_import
> ##[error]    TestAccGitlabServiceGithub_import: testing.go:654: Step 0 error: errors during apply:
>         
>         Error: PUT http://127.0.0.1:8080/api/v4/projects/25/services/github: 404 {error: 404 Not Found}
>         
>           on /tmp/tf-test931785609/main.tf line 8:
>           (source code not available)
>         
>         
> --- FAIL: TestAccGitlabServiceGithub_import (5.43s)
> ```
> 
> Any guidance for how we can separate EE-only tests from the CE test run?

Use `SkipFunc: isRunningInCE`.

**Comment by tptee** [comment]
Ok CE tests pass now–all that's left is to bump to `0.31.1` of `go-gitlab` once it's released!

I do worry that the EE tests will fail–the `SkipFunc` fails for me on my machine if I only run the single test (haven't tried running the entire suite, not sure it'll work out-of-the-box on `.com` or not yet 😄 ):

```
=== RUN   TestAccGitlabServiceGithub_basic
    TestAccGitlabServiceGithub_basic: testing.go:606: Provider not initialized, unable to get GitLab connection
--- FAIL: TestAccGitlabServiceGithub_basic (0.00s)
=== RUN   TestAccGitlabServiceGithub_import
    TestAccGitlabServiceGithub_import: testing.go:606: Provider not initialized, unable to get GitLab connection
--- FAIL: TestAccGitlabServiceGithub_import (0.00s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-gitlab/gitlab 0.036s
FAIL
```

This is with `GITLAB_TOKEN=redacted TF_ACC=1 go test -v ./gitlab -run 'TestAccGitlabServiceGithub' -timeout 40m -count 1`. Any ideas on how to run a single acceptance test that depends on `testAccProvider` being initialized? I'm sure I'm missing something obvious!

**Comment by tptee** [comment]
I ran the whole suite on a `.com` Silver plan group and the new test passed!

**Comment by tptee** [comment]
Upgraded to v0.32.0 of go-gitlab and reconfirmed the tests pass! I think this is ready to go as long as the EE tests pass for maintainers!

**Comment by tptee** [comment]
Looks like an unrelated failure from the `go-gitlab` upgrade:

```
 ##[error]    TestAccGitlabProject_basic: testing.go:654: Step 1 error: Check failed: Check 2/2 error: 1 error occurred:
        	* Check 10/28 error: attribute container_registry_enabled expected "false" received "true"
```

I'll take a peek at the changes in that release to see what's up.

**Comment by ringods** [comment]
@tptee test probably fails due to this:

https://github.com/xanzy/go-gitlab/commit/12ce54010b7d05d574aa2f870ebbfa4dcf51feea#r39607378

**Comment by ringods** [comment]
@tptee I need to ask you to rebase once more. Branch `master` already contains `go-gitlab` v0.32.1 which fixes the failing test, so please make sure you do not revert to v0.32.0.

**Comment by ringods** [comment]
@tptee Without documentation, this new resource won't show up on the Terraform website. Can you still add it to the `website/docs/r` folder? You can start of with a copy of one of the existing `service_...html.markdown` files.

**Comment by tptee** [comment]
oh whoops, on it!

**Comment by ringods** [comment]
@tptee and I forgot to mention that you also have to add the resource to the website sidebar here: `website/gitlab.erb`. Sorry for that. 😉

**Comment by tptee** [comment]
No worries! on it!

**Comment by tptee** [comment]
Done! Thanks for your patience 🙇

**Comment by ringods** [comment]
@tptee more in reverse. Thank you for all the work in this contribution.

**Pull request merged**
