### PR TITLE
Make deploy keys indempotent when newlines are added

### LINKED ISSUE #25: Deploy key is destroyed and created at each run
### Terraform Version
0.10.6

### Affected Resource(s)
- gitlab_deploy_key

### Terraform Configuration Files
```hcl
resource "gitlab_deploy_key" "default" {
  project = "group_name/project_name"
  title   = "Project Name"
  key     = "${var.deploy_key}"
}

```
### Expected Behavior
The first run should create the key, and as long as there are no changes either to the key parameter or on gitlab itself, then subsequent runs should just verify the key is the same and skip any action.

### Actual Behavior
The first run creates the key as expected, but subsequent runs always destroy and create the key rather than verifiying that it has not changed.

Looking at the code it seems that's because there is no update handler for this resource.

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by roidelapluie**
Close #25

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
My new test without the fix:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-gitlab	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGitlabDeployKey_basic
--- PASS: TestAccGitlabDeployKey_basic (6.95s)
=== RUN   TestAccGitlabDeployKey_suppressfunc
--- FAIL: TestAccGitlabDeployKey_suppressfunc (5.34s)
	testing.go:435: Step 0 error: After applying this step, the plan was not empty:
		
		DIFF:
		
		DESTROY/CREATE: gitlab_deploy_key.foo
		  can_push: "false" => "false"
		  key:      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj13ozEBZ0s4el4k6mYqoyIKKKMh9hHY0sAYqSPXs2zGuVFZss1P8TPuwmdXVjHR7TiRXwC49zDrkyWJgiufggYJ1VilOohcMOODwZEJz+E5q4GCfHuh90UEh0nl8B2R0Uoy0LPeg93uZzy0hlHApsxRf/XZJz/1ytkZvCtxdllxfImCVxJReMeRVEqFCTCvy3YuJn0bce7ulcTFRvtgWOpQsr6GDK8YkcCCv2eZthVlrEwy6DEpAKTRiRLGgUj4dPO0MmO4cE2qD4ualY01PhNORJ8Q++I+EtkGt/VALkecwFuBkl18/gy+yxNJHpKc/8WVVinDeFrd/HhiY9yU0d richardc@tamborine.example.1" => "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj13ozEBZ0s4el4k6mYqoyIKKKMh9hHY0sAYqSPXs2zGuVFZss1P8TPuwmdXVjHR7TiRXwC49zDrkyWJgiufggYJ1VilOohcMOODwZEJz+E5q4GCfHuh90UEh0nl8B2R0Uoy0LPeg93uZzy0hlHApsxRf/XZJz/1ytkZvCtxdllxfImCVxJReMeRVEqFCTCvy3YuJn0bce7ulcTFRvtgWOpQsr6GDK8YkcCCv2eZthVlrEwy6DEpAKTRiRLGgUj4dPO0MmO4cE2qD4ualY01PhNORJ8Q++I+EtkGt/VALkecwFuBkl18/gy+yxNJHpKc/8WVVinDeFrd/HhiY9yU0d richardc@tamborine.example.1\n" (forces new resource)
		  project:  "23" => "23"
		  title:    "deployKey-8819837852471578470" => "deployKey-8819837852471578470"
		
		STATE:
		
		gitlab_deploy_key.foo:
		  ID = 16
		  can_push = false
		  key = ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj13ozEBZ0s4el4k6mYqoyIKKKMh9hHY0sAYqSPXs2zGuVFZss1P8TPuwmdXVjHR7TiRXwC49zDrkyWJgiufggYJ1VilOohcMOODwZEJz+E5q4GCfHuh90UEh0nl8B2R0Uoy0LPeg93uZzy0hlHApsxRf/XZJz/1ytkZvCtxdllxfImCVxJReMeRVEqFCTCvy3YuJn0bce7ulcTFRvtgWOpQsr6GDK8YkcCCv2eZthVlrEwy6DEpAKTRiRLGgUj4dPO0MmO4cE2qD4ualY01PhNORJ8Q++I+EtkGt/VALkecwFuBkl18/gy+yxNJHpKc/8WVVinDeFrd/HhiY9yU0d richardc@tamborine.example.1
		  project = 23
		  title = deployKey-8819837852471578470
		
		  Dependencies:
		    gitlab_project.foo
		gitlab_project.foo:
		  ID = 23
		  default_branch = 
		  description = Terraform acceptance tests
		  http_url_to_repo = http://822260f7b8b1/root/foo-8819837852471578470.git
		  issues_enabled = true
		  merge_requests_enabled = true
		  name = foo-8819837852471578470
		  namespace_id = 1
		  path = foo-8819837852471578470
		  snippets_enabled = true
		  ssh_url_to_repo = git@822260f7b8b1:root/foo-8819837852471578470.git
		  visibility_level = public
		  web_url = http://822260f7b8b1/root/foo-8819837852471578470
		  wiki_enabled = true
=== RUN   TestAccGitlabGroup_basic
--- PASS: TestAccGitlabGroup_basic (0.72s)
=== RUN   TestAccGitlabGroup_import
--- PASS: TestAccGitlabGroup_import (0.31s)
=== RUN   TestAccGitlabGroup_nested
--- PASS: TestAccGitlabGroup_nested (1.69s)
=== RUN   TestAccGitlabLabel_basic
--- PASS: TestAccGitlabLabel_basic (6.27s)
=== RUN   TestAccGitlabProjectHook_basic
--- PASS: TestAccGitlabProjectHook_basic (5.97s)
=== RUN   TestAccGitlabProject_basic
--- PASS: TestAccGitlabProject_basic (5.95s)
=== RUN   TestAccGitlabProject_import
--- PASS: TestAccGitlabProject_import (5.87s)
=== RUN   TestAccGitlabProject_nestedImport
--- PASS: TestAccGitlabProject_nestedImport (5.67s)
=== RUN   TestAccGitlabUser_basic
--- PASS: TestAccGitlabUser_basic (0.57s)
=== RUN   TestGitlab_validation
--- PASS: TestGitlab_validation (0.00s)
=== RUN   TestGitlab_visbilityHelpers
--- PASS: TestGitlab_visbilityHelpers (0.00s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-gitlab/gitlab	45.312s

```

**Comment by roidelapluie** [comment]
With the fix:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-gitlab	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGitlabDeployKey_basic
--- PASS: TestAccGitlabDeployKey_basic (5.93s)
=== RUN   TestAccGitlabDeployKey_suppressfunc
--- PASS: TestAccGitlabDeployKey_suppressfunc (5.45s)
=== RUN   TestAccGitlabGroup_basic
--- PASS: TestAccGitlabGroup_basic (0.69s)
=== RUN   TestAccGitlabGroup_import
--- PASS: TestAccGitlabGroup_import (0.28s)
=== RUN   TestAccGitlabGroup_nested
--- PASS: TestAccGitlabGroup_nested (1.43s)
=== RUN   TestAccGitlabLabel_basic
--- PASS: TestAccGitlabLabel_basic (6.17s)
=== RUN   TestAccGitlabProjectHook_basic
--- PASS: TestAccGitlabProjectHook_basic (5.87s)
=== RUN   TestAccGitlabProject_basic
--- PASS: TestAccGitlabProject_basic (5.88s)
=== RUN   TestAccGitlabProject_import
--- PASS: TestAccGitlabProject_import (5.39s)
=== RUN   TestAccGitlabProject_nestedImport
--- PASS: TestAccGitlabProject_nestedImport (5.66s)
=== RUN   TestAccGitlabUser_basic
--- PASS: TestAccGitlabUser_basic (0.63s)
=== RUN   TestGitlab_validation
--- PASS: TestGitlab_validation (0.00s)
=== RUN   TestGitlab_visbilityHelpers
--- PASS: TestGitlab_visbilityHelpers (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-gitlab/gitlab	43.389s

```

**Comment by benosman** [comment]
@roidelapluie - thanks for looking into this.

I haven't built the provider with your changes, but I can confirm that wrapping the key in `trimspace()` and passing through to the resource fixes the issue for me, so it definitely looks like you've found the correct cause and your changes should fix it.

Thanks

Ben

**Comment by roidelapluie** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/blob/eb4296ba6a2f2b5521ad4dea8d0d422048ff05df/app/models/key.rb#L34-35

**Pull request merged**
