### PR TITLE
Run ACC tests

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by matejvelikonja** [comment]
this would be a really nice feature to have

any special reason why not continuing with this?

**Comment by roidelapluie** [comment]
I would love this but one test is failing and I do not know why.

**Comment by mcanevet** [comment]
@roidelapluie test is failing on my workstation also

**Comment by pdecat** [comment]
Hi, I gave it a look and those tests fail because deletion is not instantaneous.

Adding a pause in the destroy check function works around the issue:

```
diff --git a/gitlab/resource_gitlab_group_test.go b/gitlab/resource_gitlab_group_test.go
index 080c4fb..aa7fb9d 100644
--- a/gitlab/resource_gitlab_group_test.go
+++ b/gitlab/resource_gitlab_group_test.go
@@ -3,11 +3,12 @@ package gitlab
 import (
        "fmt"
        "testing"
+       "time"
 
        "github.com/hashicorp/terraform/helper/acctest"
        "github.com/hashicorp/terraform/helper/resource"
        "github.com/hashicorp/terraform/terraform"
-       "github.com/xanzy/go-gitlab"
+       gitlab "github.com/xanzy/go-gitlab"
 )
 
 func TestAccGitlabGroup_basic(t *testing.T) {
@@ -225,6 +226,7 @@ func testAccCheckGitlabGroupAttributes(group *gitlab.Group, want *testAccGitlabG
 
 func testAccCheckGitlabGroupDestroy(s *terraform.State) error {
        conn := testAccProvider.Meta().(*gitlab.Client)
+       time.Sleep(5 * time.Second)
 
        for _, rs := range s.RootModule().Resources {
                if rs.Type != "gitlab_group" {
```

```
# make testacc TEST=./gitlab TESTARGS='-run TestAccGitlabGroup_.*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./gitlab -v -run TestAccGitlabGroup_.* -timeout 120m
=== RUN   TestAccGitlabGroup_basic
--- PASS: TestAccGitlabGroup_basic (5.87s)
=== RUN   TestAccGitlabGroup_import
--- PASS: TestAccGitlabGroup_import (5.38s)
=== RUN   TestAccGitlabGroup_nested
--- PASS: TestAccGitlabGroup_nested (6.68s)
PASS
ok      github.com/terraform-providers/terraform-provider-gitlab/gitlab 17.938s
```

That's just a work-around, a better option would be to wait for actual deletion in the `resourceGitlabGroupDelete()` function.

**Comment by roidelapluie** [comment]
so we should do like for the gitlab_project:

```
	stateConf := &resource.StateChangeConf{
		Pending: []string{"Deleting"},
		Target:  []string{"Deleted"},
		Refresh: func() (interface{}, string, error) {
			out, response, err := client.Projects.GetProject(d.Id())
			if err != nil {
				if response.StatusCode == 404 {
					return out, "Deleted", nil
				}
				log.Printf("[ERROR] Received error: %#v", err)
				return out, "Error", err
			}
			return out, "Deleting", nil
		},

		Timeout:    10 * time.Minute,
		MinTimeout: 3 * time.Second,
		Delay:      5 * time.Second,
	}
```

**Comment by pdecat** [comment]
@roidelapluie :100:

My take on this is that this better fix should probably be done in another PR.

**Comment by roidelapluie** [comment]
I pushed a fix here

**Comment by roidelapluie** [comment]
how cool is this?? :)

**Comment by pdecat** [comment]
That's awesome :tada: :smile:

**Pull request merged**
