### PR TITLE
Adding new resource to manage group LDAP links

### LINKED ISSUE #183: [Feature Request]: LDAP synchronisation functionality
Hello

We would like to have the “LDAP Synchronisation" functionality for groups added to the Gitlab provider. 

Is it possible to add this feature?

Thanks,

### PR DESCRIPTION
**Pull request by jasoncarlsen**
Closes #183

### CODE REVIEW

**Comment by ringods** [comment]
@jasoncarlsen if you could also document the new resource, I will merge your contribution. Please add it in the `website/docs/r` folder. You can take any peer file in that folder as an example on how to document resources.

**Comment by jasoncarlsen** [comment]
@ringods Thanks for the feedback, I've added documentation as requested.  Please let me know if I need to change anything else.

**Comment by ringods** [comment]
@jasoncarlsen at first sight this looks fine. Tnx for the work you did in this contribution.

**Comment by ringods** [comment]
@jasoncarlsen after the merge, the acceptance tests of the Community Edition fail. One of the lines is regarding the LDAP link. Can you have a look and verify whether this is related or not?

https://github.com/terraform-providers/terraform-provider-gitlab/runs/710870254

**Comment by jasoncarlsen** [comment]
@ringods I took a look and the test is behaving as expected.  There are two things to keep in mind with this test:

1. The test is being skipped (and thus throwing the warning) because the test data is set to the default values.  I would need to know a real LDAP CN and the name of the configured LDAP provider in order to run the tests.
2. GitLab CE doesn't support LDAP links so this test should only ever be run on the against EE.

**Comment by ringods** [comment]
@jasoncarlsen If the test should be skipped on CE, could you submit an additional PR where you use `SkipFunc: isRunningInCE` in the tests?

See here for an example:
https://github.com/terraform-providers/terraform-provider-gitlab/blob/da9cca35fe74e27c7fbdb248794e42e6c47344a0/gitlab/resource_gitlab_project_push_rules_test.go#L47

**Comment by jasoncarlsen** [comment]
@ringods Done. https://github.com/terraform-providers/terraform-provider-gitlab/pull/316

**Pull request merged**
