### PR TITLE
Add shared_runners_enabled flag in project

### PR DESCRIPTION
**Pull request by kchugalinskiy**
Add new flag to enable/disable shared runners in a project. This PR doesn't require any dependency updates.

### CODE REVIEW

**Comment by kchugalinskiy** [comment]
Hello yes, one moment, please

**Comment by kchugalinskiy** [comment]
@jorcau test has been added

**Comment by iAnomaly** [comment]
@jorcau, this is an important security feature for users of GitLab.com. Based on the comments in https://github.com/terraform-providers/terraform-provider-gitlab/pull/105#issuecomment-481701071 about @kchugalinskiy's inactivity shall I fork and open a new PR with the missing `SharedRunnersEnabled` check in `func testAccCheckGitlabProjectAttributes`?

**Comment by jorcau** [comment]
Hi @iAnomaly,
This could be an option but the real problem right now is that there is no active maintainer. We still wouldn't be able to merge your new PR.

Maybe @roidelapluie could help if he has some spare time to look at it.

**Comment by roidelapluie** [comment]
Hello, I am still active, just did not had time to fix #110 

Now I have time again so we can merge new PR!

**Comment by roidelapluie** [comment]
can you add that check now?

**Comment by iAnomaly** [comment]
Done. See #134. Please close this.

**Comment by roidelapluie** [comment]
conflicts now :/

**Pull request merged**
