### PR TITLE
When changing the namespace_id, transfer project from old to new namespace

### PR DESCRIPTION
**Pull request by ringods**
This PR is work-in-progress and a request for comments.

Depends on: #245 

`go-gitlab` library supports project transferral between namespaces since version 0.22.3. With this support, it is possible to support this from the provider by checking the `namespace_id` property. If it is changed from the old value, the intent is to transfer the project.

Will add tests later, but comments on the production code is welcome.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can you please rebase?

**Comment by ringods** [comment]
@roidelapluie rebased and added an acceptance test. However, the test suite now fails on another test. Can you review and provide feedback please?

**Comment by ringods** [comment]
@roidelapluie I hope now a number of conferences are over, you have some time to review this PR so it can get integrated. 😉

**Comment by ringods** [comment]
I did a manual test with a locally built provider binary and the transfer of a repository between groups worked like a charm:

```
  # gitlab_project.example will be updated in-place
  ~ resource "gitlab_project" "example" {
        approvals_before_merge                           = 0
        archived                                         = false
        container_registry_enabled                       = true
        description                                      = "An example project"
        http_url_to_repo                                 = "https://gitlab.com/<redacted>/example.git"
        id                                               = "<redacted>"
        issues_enabled                                   = true
        lfs_enabled                                      = true
        merge_method                                     = "merge"
        merge_requests_enabled                           = true
        name                                             = "example"
      ~ namespace_id                                     = 7116509 -> 7116535
        only_allow_merge_if_all_discussions_are_resolved = false
        only_allow_merge_if_pipeline_succeeds            = false
        path                                             = "example"
        pipelines_enabled                                = true
        request_access_enabled                           = true
        runners_token                                    = "<redacted>"
        shared_runners_enabled                           = false
        snippets_enabled                                 = true
        ssh_url_to_repo                                  = "git@gitlab.com:<redacted>/example.git"
        tags                                             = []
        visibility_level                                 = "private"
        web_url                                          = "https://gitlab.com/<redacted>/example"
        wiki_enabled                                     = true
    }
```

**Comment by ringods** [comment]
@roidelapluie 🙏🏼 for a review, merge and release so it can be wrapped in a downstream Pulumi provider release.

**Comment by ringods** [comment]
Note: I can't test locally with the Docker container due to this:

https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4342

**Comment by roidelapluie** [comment]
--- FAIL: TestAccGitlabGroup_disappears (0.45s)

    testing.go:635: Step 0 error: Expected a non-empty plan, but got an empty plan!

**Comment by ringods** [comment]
@roidelapluie I know and I asked for input 19 days ago:

https://github.com/terraform-providers/terraform-provider-gitlab/pull/247#issuecomment-580593982

**Comment by ringods** [comment]
@roidelapluie latest Travis run is green!

**Comment by roidelapluie** [comment]
Yes I triggered it again

**Comment by ringods** [comment]
Strange that it works now. I haven't changed anything since the last failing run.

Did you do something which might explain the different outcome?

**Comment by roidelapluie** [comment]
nope, might be a gitlab update.

**Comment by ringods** [comment]
*sigh* Same test failing on `master` now...

**Pull request merged**
